secrets: ./creds/secrets.yml
box: ./creds/BoxApp.json
visit: 1
root:
  cache: ../tmp/cache/
  store: ../tmp/store/
config_files:
  box: ./creds/BoxApp.json
rosetta:  
  filename: '/home/petra/CCF_QC/PreRelease/HCD_Inventory_Restricted_2022-02-04.csv'
Redcap:
  api_url: https://redcap.wustl.edu/redcap/srvrs/prod_v3_1_0_001/redcap/api/
  datasources:
    qint:
      event_names:
          - V1
          - V2
          - V3
      visit:
        - 1
        - 2
        - 3
    PennCNP:
      visit:
        - 1
        - 2
        - 3
      events:
        - V1
        - V2
        - V3
    hcpa:
      events: 
        - visit_1_arm_1
        - visit_2_arm_1
      event_names:
        - V1
        - V2
      fields:
        idvar: id
        dobvar: dob
        field: subject_id
        interview_date: v1_date
        sexatbirth: gender
        sitenum: site
    teen:
      events:
        - visit_arm_1
      event_names:
        - V1
      fields:
        #eventvar: redcap_event_name
        idvar: id
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    child:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
        - visit_3_arm_1
      event_names:
        - V1
        - V2
        - V3
      fields:
        idvar: id
        #eventvar: redcap_event_name
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    parent:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
        - visit_3_arm_1
      event_names:
        - V1
        - V2
        - V3
      fields:
        idvar: id
        field: parent_id
        interview_date: intake_date
        #eventvar: redcap_event_name
        sexatbirth: gender
        sitenum: site

  behavioral:
    hcpa:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
      event_names:
        - V1
        - V2
      fields:
        idvar: id
        #eventvar: redcap_event_name
        dobvar: dob
        field: subject_id
        interview_date: v1_date
        sexatbirth: gender
        sitenum: site
    teen:
      events:
        - visit_arm_1
      event_names:
        - V1
      fields:
        #eventvar: redcap_event_name
        idvar: id
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    child:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
        - visit_3_arm_1
      event_names:
        - V1
        - V2
        - V3
      fields:
        idvar: id
        #eventvar: redcap_event_name
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    parent:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
        - visit_3_arm_1
      event_names:
        - V1
        - V2
        - V3
      fields:
        idvar: id
        field: parent_id
        interview_date: intake_date
        #eventvar: redcap_event_name
        sexatbirth: gender
        sitenum: site

