secrets: ./creds/secrets.yml
box: ./creds/BoxApp.json
visit: 1
root:
  cache: ../tmp/cache/
  store: ../tmp/store/
config_files:
  box: ./creds/BoxApp.json
rosetta:  
  filename: 'HCA_AllSources_11_19_2021.csv'
Redcap:
  api_url: https://redcap.wustl.edu/redcap/srvrs/prod_v3_1_0_001/redcap/api/
  datasources:
    qint:
      visit:
        - 1
        - 2
        - 3
    hcpa:
      events: 
        - visit_1_arm_1
        - visit_2_arm_1
      fields:
        idvar: id
        eventvar: redcap_event_name
        dobvar: dob
        field: subject_id
        interview_date: v1_date
        sexatbirth: gender
        sitenum: site
  behavioral:
    hcpa:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
      fields:
        idvar: id
        eventvar: redcap_event_name
        dobvar: dob
        field: subject_id
        interview_date: v1_date
        sexatbirth: gender
        sitenum: site
    teen:
      events:
        - visit_arm_1
      fields:
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    child:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
        - visit_3_arm_1
      fields:
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    parent:
      events:
        - visit_1_arm_1
        - visit_2_arm_1
        - visit_3_arm_1
      fields:
        field: parent_id
        #interview_date: intake_date
        sexatbirth: gender
        sitenum: site

